pybo/views/answer_views.py
from datetime import datetime

from flask import Blueprint, url_for, request, render_template, g
from werkzeug.utils import redirect

from pybo import db
from pybo.models import Question, Answer
from pybo.forms import AnswerForm

from .auth_views import login_required

bp = Blueprint('answer', __name__, url_prefix='/answer')


@bp.route('/create/<int:question_id>', methods=('POST',))
@login_required
def create(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    if form.validate_on_submit():
        content = request.form['content']
        answer = Answer(content=content, create_date=datetime.now(), user=g.user)
        question.answer_set.append(answer)
        db.session.commit()
        return redirect(url_for('question.detail', question_id=question_id))
    return render_template('question/question_detail.html', question=question, form=form)

pybo/views/question_views.py
import os
from pybo import create_app
from flask import Blueprint, render_template, request,  url_for, g, flash
from pybo.models import Question
from pybo.forms import QuestionForm, AnswerForm
from pybo import db
from werkzeug.utils import redirect, secure_filename
from datetime import datetime
from pybo.views.auth_views import login_required

bp = Blueprint('question', __name__, url_prefix='/question')

def allowed_file(filename):
    return'.' in filename and \
        filename.rsplit('.', 1)[1].lower() in {'jpg', 'jpeg', 'png', 'webp', 'gif'}

@bp.route('/list/')
def _list():
    page = request.args.get('page', type = int,default=1)
    question_list = Question.query.order_by(Question.create_date.desc())
    question_list = question_list.paginate(page=page, per_page=10)
    return render_template('question/question_list.html', question_list=question_list)


@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html', question=question, form=form)

@bp.route('/create/', methods = ('GET','POST'))
@login_required
def create():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        if 'uploaded_img_file' in request.files:
            file = request.files['uploaded_img_file']
            if file and allowed_file(file.filename):
                filename = secure_filename(file.filename)
                app = create_app()
                file_path = os.path.join(app.config['UPLOAD_FOLDER'], secure_filename(filename))
                file_path_abs = os.path.join(os.path.abspath(os.path.dirname(__file__)), app.config['UPLOAD_FOLDER'],secure_filename(filename))
                file.save(file_path_abs) #disk
                question = Question(subject=form.subject.data, content=form.content.data,
                                    uploaded_img_file=file_path, #DB
                                    create_date=datetime.now(),user=g.user)
                db.session.add(question)
                db.session.commit()
                return redirect(url_for('main.index'))
            else:
                flash('attached image file format is not allowed')
        else:
            flash('image file is not attached')
    return render_template('question/question_form.html', form=form)

@bp.route('/modify/<int:question_id>', methods=('GET', 'POST'))     #20230722
@login_required
def modify(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash("You don't have permission to edit")
        return redirect(url_for('question.detail', question_id=question_id))
    if request.method == 'POST':  # POST 요청
        form = QuestionForm()
        if form.validate_on_submit():
            form.populate_obj(question)
            question.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return redirect(url_for('question.detail', question_id=question_id))
    else:  # GET 요청
        form = QuestionForm(obj=question)
    return render_template('question/question_form.html', form=form)        #20230722

@bp.route('/delete/<int:question_id>')
@login_required
def delete(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash("You don't have permission to delete")
        return redirect(url_for('question.detail', question_id=question_id))
    db.session.delete(question)
    db.session.commit()
    return redirect(url_for('question._list'))

pybo/templates/question/question_detail.html
{% extends 'base.html' %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
<div class="container my-3">
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ question.create_date }}
                </div>
            </div>
            <div class="my-3">
                {% if g.user == question.user %}
                <a href="{{ url_for('question.modify', question_id=question.id) }}"
                   class="btn btn-sm btn-outline-secondary">Change</a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{{ url_for('question.delete', question_id=question.id) }}">Delete</a>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- 답변 목록 -->
    <h5 class="border-bottom my-3 py-2">There is {{ question.answer_set|length }} question.</h5>
    {% for answer in question.answer_set %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{{ url_for('answer.create', question_id=question.id) }}" method="post" class="my-3">
        {{ form.csrf_token }}

        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field,errors in form.error.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li> {{ error }} </li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}

        <div class="mb-3">
            <textarea {% if not g.user %}disabled{% endif %} name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <div class="mb-3">
            <img src="{{ '../../' + question.uploaded_img_file }}" alt="Uploaded Image" width="300" height="200">
        </div>
        <input {% if not g.user %}disabled{% endif %} type="submit" value="Register Reply" class="btn btn-primary">
    </form>
</div>

{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("Are you sure to delete this?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

pybo/templates/question/question_form.html
{% extends 'base.html' %}
{% block content %}

<!-- 질문 등록 -->
<div class="container">
    <h5 class="my-3 border-bottom pb-2">Register question</h5>
    <form method="post" class="my-3" enctype="multipart/form-data">
        {{ form.csrf_token }}
       <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->

        <div class="mb-3">
            <label for="subject">Title</label>
            <input type="text" class="form-control" name="subject" id="subject"
                value="{{ form.subject.data or '' }}">
        </div>
        <div class="mb-3">
            <label for="content">Detail</label>
            <textarea class="form-control" name="content"
                id="content" rows="10">{{ form.content.data or '' }}</textarea>
        </div>
        <!-- 20231230 -->
        <div class="mb-3">
            <label for="uploaded_img_file" >Attachment</label>
            <input type="file" class="form-control" name="uploaded_img_file" id="uploaded_img_file">
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

pybo/templates/question/question_list.html
{% extends 'base.html' %}
{% block content %}


<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th>Number</th>
            <th style="width=50"> Title</th>
            <th>Writer</th>
            <th>Date</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{ loop.index }}</td>
            <td>
                <a href="{{ url_for('question.detail', question_id=question.id) }}">{{ question.subject }}</a>
                {% if question.answer_set|length > 0 %}
                <span class="text-danger small mx-2">{{ question.answer_set|length }}</span>
                {% endif %}
            </td>
            <td>{{ question.user.username }}</td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">There is no question.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <a href="{{ url_for('question.create') }}" class = "btn btn-primary">Register a question</a>

    <!-- 페이징 처리 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_prev %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.prev_num }}">Previous page</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">Previous page</a>
        </li>
        {% endif %}
        <!-- 페이지번호 -->
        {% for page_num in question_list.iter_pages() %}
        {% if page_num %}
        {% if page_num != question_list.page %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="disabled">
            <a class="page-link" href="javascript:void(0)">...</a>
        </li>
        {% endif %}
        {% endfor %}

        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_num }}">Next page</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">Next page</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징 처리 끝-->

</div>

{% endblock %}